In [37]:
pip install pandas

Requirement already satisfied: pandas in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (2.3.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pytz>=2020.1 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import pandas as pd

In [39]:
train_data = pd.read_csv('train.csv')

In [40]:
train_data = train_data[['Id', 'GrLivArea', 'SalePrice']]

In [41]:
train_data.head()

   Id  GrLivArea  SalePrice
0   1       1710     208500
1   2       1262     181500
2   3       1786     223500
3   4       1717     140000
4   5       2198     250000

In [42]:
train_data.describe()

                Id    GrLivArea      SalePrice
count  1460.000000  1460.000000    1460.000000
mean    730.500000  1515.463699  180921.195890
std     421.610009   525.480383   79442.502883
min       1.000000   334.000000   34900.000000
25%     365.750000  1129.500000  129975.000000
50%     730.500000  1464.000000  163000.000000
75%    1095.250000  1776.750000  214000.000000
max    1460.000000  5642.000000  755000.000000

In [ ]:
split_at = int(0.8 * len(train_data))

train_rows = train_data.iloc[:split_at]
validation_rows = train_data.iloc[split_at:]


x_train = train_rows['GrLivArea'].to_numpy() / 1000
y_train = train_rows['SalePrice'].to_numpy() / 1000

In [44]:
x_train = x_train[:3]
y_train = y_train[:3]

In [45]:
x_train

array([1.71 , 1.262, 1.786])

In [46]:
y_train

array([208.5, 181.5, 223.5])

In [47]:
# I want to leverage the gradient descent to find the best parameters and make the most accurate predictions

# Since this is a single variable linear regression model, I have two choices
# 1 Direct calculation of w, b
# 2 Leverage Gradient Descent to find the w, b


# 1 Direct Calculation
# step 1: calculate the partial derivative of J relative to w and b
# step 2: plug one partial derivative into the other and solve two equations to find both w, b
# step 3: make predictions
        # Predictions can be made in two ways
            # 1 Using a for loop
            # 2 Using vectorization
            

import numpy as np


x_mean = x_train.mean()
y_mean = y_train.mean()

best_w_dir = np.sum((x_train - x_mean) * (y_train - y_mean)) / np.sum((x_train - x_mean)**2)
best_b_dir = y_mean - best_w_dir * x_mean

# Making predictions using vectorization
predictions = best_w_dir * x_train + best_b_dir # ~ y_train

print('prediction - via vectorization', predictions)

prediction - via vectorization [213.58471363 180.76252245 219.15276392]

In [48]:

# Leveraging Gradient Descent to find the best model parameters

m = len(x_train)
dj_dw, dj_db = 0, 0
w, b = 0, 0
learning_rate = 0.01
for iter in range(2000):

    w = w - learning_rate * dj_dw
    b = b - learning_rate * dj_db

    error_sqrd = 0
    dj_dw_val, dj_db_val = 0, 0
    for i in range(m):
        y_hat = w * x_train[i] + b
        error_sqrd += (y_hat - y_train[i])**2

        dj_dw_val += (y_hat - y_train[i]) * x_train[i]
        dj_db_val += (y_hat - y_train[i])


    cost = error_sqrd / (2 * m)
    dj_dw = dj_dw_val / m
    dj_db = dj_db_val / m

    print(iter, w, b, cost) 

predictions = []

for i in range(m):
    predictions.append(w * x_train[i] + b)

print(predictions)

0 0.0 0.0 21061.125
1 3.28253 2.045 19591.99931726408
2 6.448303137512667 4.0174890742 18225.437749783752
3 9.5014687405913 5.920044095697049 16954.279971459506
4 12.446028678206488 7.755150360514301 15771.865541265352
5 15.285842600656247 9.525204842072803 14671.999004686499
6 18.024632993742102 11.232519330005667 13648.917431536354
7 20.66599005332957 12.87932345742486 12697.260220061413
8 23.213376386676188 14.467767620604805 11812.041009117404
9 25.67013154668348 15.999925794906073 10988.62155124546
10 28.03947640501034 17.477798250626613 10222.687409751745
11 30.324517369774508 18.903314172336884 9510.22535245097
12 32.52825045336504 20.27833418512889 8847.502323624414
13 34.65356519569264 21.604652791087233 8231.045884012234
14 36.70324844801529 22.884000719172676 7657.626016351929
15 38.67998802229398 24.118047191595426 7124.238201129888
16 40.586376210857516 25.30840210964589 6628.087673868385
17 42.42491318098513 26.45661816184523 6166.574781461289
18 44.1980102488523 27.564192857176355 5737.281360830445
19 45.90799303712685 28.632570486057794 5337.958068531224
20 47.55710452035017 29.663144011628383 4966.512594918508
21 49.147507962091545 30.657256893819344 4620.998701119126
22 50.68128974772165 31.61620484860238 4299.606021367999
23 52.16046211651479 32.54123754471749 4000.6505772755686
24 53.58696579665755 33.43356024010239 3722.5659543242655
25 54.962672546614286 34.29433536016637 3463.8950943617624
26 56.28938760617743 35.124684019975405 3223.2826610863085
27 57.56885206041225 35.92568749234168 2999.467938521724
28 58.80274511959154 36.69838862374012 2791.278225272394
29 59.9926863181059 37.443793199906 2597.6226899462695
30 61.14023763522894 38.162871262901774 2417.486655550268
31 62.24690554051466 38.85655838137802 2249.926282910165
32 63.314142966505344 39.52575687569168 2094.0636252577956
33 64.34335121133323 40.17133699948599 1949.0820280732253
34 65.33588177370743 40.794138079279385 1814.2218500785045
35 66.2930381226889 41.39496961355559 1688.7764829624412
36 67.21607740457115 41.97461233279419 1572.0886489809884
37 68.10621208910162 42.533819221829745 1463.5469570339176
38 68.96461155719958 43.073316505878296 1362.582699172676
39 69.7924036322496 43.59380460152233 1268.6668707542046
40 70.59067605697587 44.095959033899625 1181.307398627265
41 71.36047791783113 44.58043132129699 1100.0465628278696
42 72.10282101876575 45.04784982830722 1024.45859827433
43 72.8186812061756 45.498820588666526 954.1474638955829
44 73.50899964676388 45.93392809884992 888.7447675037332
45 74.17468405999021 46.353736083463744 827.9078355378441
46 74.81660990672088 46.75878823343766 771.3179175650148
47 75.43562153563676 47.14960891798269 718.6785161309467
48 76.03253328890007 47.52670387124766 669.7138332089286
49 76.60813056852795 47.89056085457323 624.167325107157
50 77.16317086486914 48.24165029521065 581.800358262545
51 77.69838474853061 48.580425902341716 542.3909588778397
52 78.214476827053 48.9073252612066 505.732649850532
53 78.71212666758774 49.222770406117476 471.63336889945094
54 79.19198968678394 49.52716837310836 439.9144622203703
55 79.65469800905048 49.820911732944886 410.409748397707
56 80.10086129431708 50.104379105191896 382.9646476675163
57 80.53106753637839 50.377935654012106 357.43537196939786
58 80.94588383286641 50.641933566345024 333.68817154344384
59 81.34585712785972 50.89671251309231 311.59863412464637
60 81.73151492810162 51.14260009391353 291.0510330627655
61 82.10336599376544 51.3799122662147 271.9377209520167
62 82.46190100467129 51.60895375889144 254.15856559339238
63 82.80759320282681 51.83001847136844 237.62042533424133
64 83.14089901213319 52.04338985845792 222.23666103606092
65 83.46225863606817 52.24934130154091 207.92668211335732
66 83.77209663412839 52.44813646655746 194.6155242649818
67 84.0708224777862 52.64002964927461 182.2334566853747
68 84.35883108668884 52.825266108284175 170.7156166976405
69 84.63650334580208 53.00408238616645 160.00166989404852
70 84.90420660417563 53.17670661924036 150.03549400319983
71 85.16229515598333 53.34335883630573 140.76488482743162
72 85.41111070446821 53.50425124676878 132.1412827096647
73 85.65098280939975 53.659588518528224 124.11951809646608
74 85.88222931862938 53.80956804598586 116.65757486416118
75 86.10515678430941 53.95438020853254 109.71637016790369
76 86.32006086432025 54.09420861984807 103.25954966017598
77 86.52722670943173 54.22923036834147 97.25329700573813
78 86.72692933670548 54.35961624904647 91.66615669494082
79 86.9194339896273 54.48553098727585 86.46886922700486
80 87.10499648544102 54.6071334543276 81.6342177996771
81 87.28386355013902 54.72457687552523 77.13688570196685
82 87.45627314154756 54.838009030864775 72.95332366275072
83 87.6224547609305 54.94757244853118 69.0616264601885
84 87.78262975351912 55.053404591537515 65.44141814542981
85 87.93701159836172 55.15563803773133 62.0737452792161
86 88.0858061878725 55.254400653404 58.940977621975314
87 88.2292120974459 55.3498157607303 56.02671575705411
88 88.3674208454892 55.44200229925751 53.31570516306752
89 88.50061714421433 55.53107498165548 50.793756285128836
90 88.6289791415167 55.617144443931686 48.44767018616127
91 88.75267865425839 55.700317390307916 46.26516938872658
92 88.87188139326081 55.7806967329483 44.23483354500507
93 88.9867471803015 55.8583817267217 42.34603959785978
94 89.09743015739943 55.9334680991749 40.58890611944361
95 89.2040789886625 56.0060481758868 38.954241535708235
96 89.30683705496197 56.07621100136774 37.43349596552185
97 89.40584264168847 56.144042455662365 36.018716422051206
98 89.5012291198354 56.20962536680856 34.702505141678394
99 89.59312512064723 56.27303961929989 33.47798082210688
100 89.68165470406089 56.334362258693425 32.338742566558786
101 89.76693752116124 56.39366759250009 31.278836345142015
102 89.8490889708631 56.45102728748947 30.29272379765601
103 89.92822035102513 56.506510463536685 29.375253214372034
104 90.00443900419347 56.56018378413406 28.52163254273753
105 90.07784845816585 56.61211154368621 27.727404278568397
106 90.14854856156033 56.66235575170284 26.98842211016566
107 90.2166356145663 56.710976213999466 26.300829192981922
108 90.28220249504867 56.75803061101245 25.661037941001126
109 90.3453387801707 56.803574573330856 25.06571122894645
110 90.40613086369456 56.84766175454404 24.51174490682205
111 90.46466206911316 56.89034390150041 23.9962515351697
112 90.52101275876169 56.931670922069266 23.516545255818887
113 90.5752604390513 56.97169095049461 23.0701277188577
114 90.62747986196324 57.01045041042631 22.654674992086893
115 90.67774312293582 57.04799407571131 22.26802538436611
116 90.72611975527295 57.084365129024434 21.90816811905066
117 90.77267682119728 57.11960521841556 21.57323279817278
118 90.81747899966777 57.15375451184721 21.261479602160275
119 90.86058867107621 57.18685174979401 20.97129017374469
120 90.90206599893384 57.2189342959728 20.701159138293153
121 90.94196900865497 57.25003818626998 20.449686216131752
122 90.98035366354085 57.28019817593002 20.21556888553356
123 91.01727393806318 57.30944778506696 19.99759555792586
124 91.05278188854322 57.3378193425586 19.794639229558733
125 91.08692772131913 57.36534402838072 19.60565157637005
126 91.11975985849082 57.39205191443679 19.4296574611071
127 91.15132500132835 57.41797200393676 19.2657498239231
128 91.18166819142678 57.44313226937633 19.113084929678053
129 91.21083286968795 57.467559689166535 18.970877947039295
130 91.23886093320588 57.49128028296162 18.838398836220932
131 91.26579279013082 57.514319145731356 18.71496852381158
132 91.29166741258334 57.53670048062257 18.59995534465003
133 91.3165223876881 57.55844763065277 18.49277173210542
134 91.3403939667939 57.57958310927751 18.39287113941855
135 91.36331711294457 57.60012862987138 18.29974517597492
136 91.38532554666284 57.62010513416136 18.212920943502947
137 91.40645179010711 57.63953281964968 18.131958558241028
138 91.42672720965903 57.65843116606209 18.056448846090166
139 91.44618205699754 57.676818960856274 17.986011198674678
140 91.46484550871325 57.69471432382373 17.920291579078633
141 91.48274570451501 57.712134730817304 17.858960666808056
142 91.49990978407867 57.72909703663552 17.80171213225885
143 91.51636392258632 57.74561749709368 17.748261031650195
144 91.53213336500252 57.76171179031053 17.698342314012077
145 91.54724245913245 57.777395037238485 17.651709432405628
146 91.56171468750517 57.79268182146426 17.608133052097184
147 91.57557269812393 57.80758620830578 17.567399848920616
148 91.58883833412354 57.82212176323048 17.529311391527973
149 91.60153266237384 57.836301569618975 17.493683101675256
150 91.61367600106672 57.85013824589753 17.460343287092968
151 91.62528794632259 57.86364396206164 17.429132241875497
152 91.63638739785145 57.87683045561234 17.399901409674996
153 91.64699258370197 57.88970904692629 17.37251260531536
154 91.65712108413105 57.902290654079515 17.346837290747953
155 91.66678985462502 57.9145858071444 17.322755901555055
156 91.67601524810284 57.9266046619786 17.300157220472
157 91.68481303633014 57.938357013523905 17.27893779464624
158 91.69319843057232 57.94985230863247 17.25900139357903
159 91.7011861015136 57.96109965843727 17.24025850490985
160 91.70879019846825 57.97210785028289 17.222625865402158
161 91.71602436790909 57.982885359232355 17.20602602467189
162 91.72290177133743 57.99344035916499 17.190386939374367
163 91.72943510251814 58.00378073347993 17.175641595720773
164 91.73563660410194 58.01391408541919 17.161727658349974
165 91.74151808365727 58.02384774802394 17.148587143711882
166 91.74709092913218 58.0335887937369 17.136166116254373
167 91.75236612376688 58.04314404366349 17.124414405818825
168 91.75735426047619 58.05252007650391 17.11328534476718
169 91.76206555572107 58.06172323716772 17.102735523458737
170 91.76650986288696 58.070759645082305 17.092724562800125
171 91.77069668518685 58.07963520220609 17.083214902672204
172 91.77463518810566 58.08835560075697 17.074171605129326
173 91.77833421140251 58.096926330666044 17.06556217133651
174 91.78180228068634 58.10535268676654 17.057356371287792
175 91.78504761858022 58.11363977572719 17.049526085411905
176 91.78807815548888 58.121792522739234 17.042045157236114
177 91.79090153998357 58.12981567796579 17.03488925633612
178 91.79352514881788 58.13771382276199 17.028035750854027
179 91.79595609658763 58.14549137567412 17.02146358891571
180 91.79820124504745 58.153152598225496 17.015153188327368
181 91.80026721209623 58.160701600496786 17.00908633397239
182 91.80216038044333 58.16814234650797 17.00324608237138
183 91.8038869059667 58.17547865940906 16.997616672905185
184 91.80545272577412 58.18271422648634 16.992183445235586
185 91.80686356597775 58.1898526039907 16.986932762491485
186 91.80812494919262 58.19689722179439 16.981851939816867
187 91.80924220176846 58.203851387882246 16.976929177908037
188 91.81022046076458 58.210718292683374 16.972153501190466
189 91.81106468067695 58.217501013248814 16.967514700311433
190 91.81177963992607 58.22420251728079 16.963003278647587
191 91.81236994711442 58.23082566701875 16.95861040254747
192 91.81284004706139 58.23737322298733 16.954327855046735
193 91.81319422662388 58.243847847611065 16.95014799281583
194 91.81343662030994 58.2502521087007 16.946063706112394
195 91.813571215693 58.25658848281558 16.942068381530177
196 91.81360185863359 58.26285935850653 16.938155867347763
197 91.81353225831556 58.269067039443534 16.934320441297388
198 91.81336599210333 58.27521374743221 16.930556780583068
199 91.81310651022645 58.28130162532313 16.92685993399243
200 91.81275714029775 58.28733273981771 16.92322529595517
201 91.81232109167094 58.29330908417441 16.91964858241272
202 91.81180145964325 58.29923258081877 16.916125808372435
203 91.8112012295088 58.30510508386064 16.91265326702914
204 91.8105232804679 58.310928381522025 16.909227510343694
205 91.80977038939744 58.31670419847858 16.905845330977638
206 91.80894523448721 58.32243419811795 16.90250374548941
207 91.80805039874711 58.32811998471781 16.89919997870325
208 91.80708837338962 58.3337631055465 16.89593144916954
209 91.80606156109211 58.33936505288908 16.892695755640194
210 91.80497227914323 58.344927266001264 16.889490664488264
211 91.80382276247742 58.35045113299404 16.886314098005325
212 91.80261516660167 58.35593799265121 16.883164123517187
213 91.80135157041815 58.36138913618239 16.880038943257773
214 91.80003397894666 58.36680580891373 16.876936884951387
215 91.79866432595024 58.3721892119185 16.873856393051227
216 91.79724447646751 58.37754050358975 16.870796020590706
217 91.795776229255 58.38286080115708 16.867754421602914
218 91.79426131914263 58.38815118214952 16.864730344069475
219 91.79270141930566 58.393412685806425 16.86172262336166
220 91.79109814345564 58.398646314438174 16.858730176139776
221 91.78945304795377 58.40385303473859 16.855751994677828
222 91.78776763384889 58.40903377905066 16.852787141584447
223 91.78604334884326 58.41418944658731 16.849834744893318
224 91.78428158918841 58.41932090460878 16.846893993495122
225 91.7824837015135 58.424428989558166 16.843964132888882
226 91.7806509845889 58.42951450815658 16.841044461230396
227 91.77878469102696 58.43457823845943 16.83813432565561
228 91.77688602892236 58.43962093087515 16.83523311886159
229 91.77495616343424 58.44464330914769 16.8323402759255
230 91.77299621831199 58.44964607130415 16.829455271345918
231 91.77100727736688 58.45462989056868 16.826577616290837
232 91.7689903858914 58.45959541624396 16.823706856037756
233 91.76694655202814 58.46454327456128 16.8208425675917
234 91.76487674809005 58.4694740695005 16.81798435747154
235 91.76278191183368 58.47438838358079 16.815131859648016
236 91.76066294768735 58.4792867786233 16.812284733628683
237 91.75852072793549 58.484169796486746 16.809442662673792
238 91.756356093861 58.48903795977682 16.806605352139083
239 91.754169856847 58.49389177253042 16.803772527932534
240 91.75196279943938 58.49873172087552 16.80094393508024
241 91.74973567637166 58.50355827366766 16.798119336390865
242 91.74748921555333 58.50837188310373 16.795298511214934
243 91.7452241190232 58.513172985314014 16.792481254289616
244 91.74294106386874 58.51796200093317 16.789667374664514
245 91.74064070311279 58.522739335650876 16.78685669470291
246 91.7383236665688 58.527505380743 16.784049049151616
247 91.73599056166569 58.53226051358379 16.781244284276955
248 91.73364197424326 58.537005098139936 16.778442257060536
249 91.73127846931948 58.54173948544704 16.77564283445098
250 91.72890059183045 58.54646401406916 16.772845892667963
251 91.7265088673441 58.551179010542036 16.77005131655549
252 91.72410380274843 58.55588478980054 16.76725899897945
253 91.72168588691542 58.560581655590944 16.764468840267618
254 91.71925559134125 58.56526990086856 16.7616807476887
255 91.71681337076383 58.5699498081812 16.758894634967778
256 91.71435966375832 58.57462165003907 16.756110421835775
257 91.71189489331157 58.57928568927147 16.753328033610025
258 91.70941946737605 58.58394217937084 16.750547400804326
259 91.7069337794042 58.588591364824545 16.747768458765716
260 91.70443820886365 58.59323348143495 16.74499114733787
261 91.7019331217343 58.597868756628024 16.742215410546667
262 91.69941887098761 58.60249740975104 16.739441196308054
263 91.6968957970489 58.607119652359664 16.7366684561572
264 91.69436422824317 58.611735688494875 16.73389714499487
265 91.69182448122523 58.616345714949986 16.731127220853367
266 91.68927686139432 58.62094992152826 16.728358644677204
267 91.68672166329418 58.62554849129126 16.725591380120232
268 91.68415917099883 58.6301416007985 16.72282539335646
269 91.6815896584846 58.63472942033847 16.720060652903737
270 91.67901338998904 58.63931211415152 16.717297129460825
271 91.67643062035697 58.64388984064478 16.714534795754517
272 91.67384159537433 58.64846275259947 16.71177362639808
273 91.67124655209004 58.65303099737084 16.709013597760293
274 91.66864571912659 58.65759471708098 16.706254687841774
275 91.66603931697942 58.66215404880482 16.70349687616208
276 91.6634275583058 58.66670912474948 16.70074014365298
277 91.66081064820332 58.67126007242726 16.697984472560197
278 91.65818878447861 58.67580701482248 16.695229846351978
279 91.6555621579064 58.68035007055243 16.69247624963267
280 91.65293095247947 58.68488935402251 16.689723668064747
281 91.6502953456496 58.68942497557596 16.686972088294056
282 91.64765550856009 58.6939570416382 16.68422149788139
283 91.64501160626992 58.69848565485606 16.681471885238977
284 91.64236379796995 58.70301091423205 16.678723239570257
285 91.63971223719153 58.70753291525393 16.675975550815647
286 91.63705707200758 58.71205175001953 16.673228809600197
287 91.63439844522657 58.7165675073573 16.670483007186267
288 91.63173649457963 58.72108027294243 16.667738135428994
289 91.62907135290097 58.72559012940897 16.66499418673493
290 91.62640314830192 58.73009715645787 16.66225115402337
291 91.62373200433878 58.73460143096123 16.659509030690714
292 91.62105804017467 58.739103027062804 16.656767810577175
293 91.6183813707357 58.743602016275005 16.654027487935746
294 91.61570210686149 58.74809846757239 16.65128805740349
295 91.61302035545042 58.752592447481845 16.64854951397425
296 91.61033621959972 58.757084020169586 16.645811852974653
297 91.60764979874051 58.761573247525035 16.643075070040172
298 91.60496118876814 58.76606018924176 16.640339161093582
299 91.60227048216781 58.77054490289548 16.637604122325317
300 91.59957776813573 58.775027444019344 16.634869950174416
301 91.59688313269609 58.779507866176516 16.632136641311508
302 91.59418665881371 58.78398622103019 16.629404192622214
303 91.59148842650279 58.788462558411105 16.62667260119267
304 91.58878851293179 58.79293692638266 16.62394186429486
305 91.58608699252453 58.797409371303736 16.62121197937446
306 91.58338393705775 58.80187993788926 16.61848294403807
307 91.58067941575518 58.80634866926863 16.615754756042175
308 91.57797349537827 58.810815607042066 16.613027413282946
309 91.57526624031368 58.81528079133495 16.610300913785913
310 91.57255771265768 58.81974426085022 16.60757525569771
311 91.56984797229758 58.82420605291897 16.604850437276852
312 91.56713707699018 58.82866620354914 16.60212645688644
313 91.56442508243752 58.83312474747258 16.599403312986748
314 91.56171204235991 58.8375817181904 16.596681004128328
315 91.55899800856632 58.842037148016665 16.593959528945955
316 91.55628303102232 58.846491068120635 16.59123888615238
317 91.55356715791561 58.85094350856741 16.58851907453325
318 91.55085043571918 58.85539449835719 16.585800092941664
319 91.54813290925227 58.859844065463115 16.58308194029392
320 91.54541462173913 58.86429223686774 16.5803646155649
321 91.54269561486568 58.86873903859828 16.57764811778372
322 91.53997592883422 58.873184495760526 16.57493244603041
323 91.53725560241614 58.87762863257161 16.57221759943177
324 91.53453467300274 58.88207147239157 16.569503577158915
325 91.53181317665434 58.886513037753836 16.566790378423672
326 91.52909114814751 58.89095335039456 16.564078002475615
327 91.52636862102078 58.895392431280996 16.56136644859971
328 91.52364562761852 58.8998303006388 16.55865571611383
329 91.5209221991335 58.90426697797838 16.555945804366342
330 91.51819836564772 58.90870248212034 16.553236712734204
331 91.51547415617196 58.913136831219965 16.550528440620695
332 91.5127495986838 58.91757004279088 16.54782098745381
333 91.51002472016434 58.922002133727844 16.545114352684283
334 91.50729954663363 58.92643312032876 16.54240853578433
335 91.50457410318484 58.93086301831586 16.53970353624582
336 91.50184841401715 58.93529184285619 16.53699935357904
337 91.49912250246759 58.93971960858131 16.534295987311978
338 91.4963963910416 58.94414632960636 16.53159343698774
339 91.49367010144265 58.94857201954838 16.52889170216496
340 91.4909436546007 58.952996691544016 16.52619078241584
341 91.48821707069972 58.95742035826661 16.523490677325494
342 91.48549036920417 58.96184303194265 16.520791386490888
343 91.48276356888461 58.96626472436765 16.518092909520394

In [49]:

# Leveraging Gradient Descent to find the best model parameters

m = len(x_train)
dj_dw, dj_db = 0, 0
w, b = 0, 0
learning_rate = 0.01
for iter in range(2000):

    w = w - learning_rate * dj_dw
    b = b - learning_rate * dj_db

    error_sqrd = 0
    dj_dw_val, dj_db_val = 0, 0

    y_hat = w * x_train + b
    error = np.sum(((y_hat - y_train)**2 )) / ( 2 * m )
    dj_dw = np.sum((y_hat - y_train) * x_train) / m
    dj_db = np.sum(y_hat - y_train) / m


    print(iter, w, b, error) 

predictions = w * x_train + b
print(predictions)

0 0.0 0.0 21061.125
1 3.28253 2.045 19591.99931726408
2 6.448303137512667 4.0174890742 18225.437749783752
3 9.5014687405913 5.920044095697049 16954.279971459506
4 12.446028678206488 7.755150360514301 15771.865541265352
5 15.285842600656247 9.525204842072803 14671.999004686499
6 18.024632993742102 11.232519330005667 13648.917431536354
7 20.66599005332957 12.87932345742486 12697.260220061413
8 23.213376386676188 14.467767620604805 11812.041009117404
9 25.67013154668348 15.999925794906073 10988.62155124546
10 28.03947640501034 17.477798250626613 10222.687409751745
11 30.324517369774508 18.903314172336884 9510.22535245097
12 32.52825045336504 20.27833418512889 8847.502323624414
13 34.65356519569264 21.604652791087233 8231.045884012234
14 36.70324844801529 22.884000719172676 7657.626016351929
15 38.67998802229398 24.118047191595426 7124.238201129888
16 40.586376210857516 25.30840210964589 6628.087673868385
17 42.42491318098513 26.45661816184523 6166.574781461289
18 44.1980102488523 27.564192857176355 5737.281360830445
19 45.90799303712685 28.632570486057794 5337.958068531224
20 47.55710452035017 29.663144011628383 4966.512594918508
21 49.147507962091545 30.657256893819344 4620.998701119126
22 50.68128974772165 31.61620484860238 4299.606021367999
23 52.16046211651479 32.54123754471749 4000.6505772755686
24 53.58696579665755 33.43356024010239 3722.5659543242655
25 54.962672546614286 34.29433536016637 3463.8950943617624
26 56.28938760617743 35.124684019975405 3223.2826610863085
27 57.56885206041225 35.92568749234168 2999.467938521724
28 58.80274511959154 36.69838862374012 2791.278225272394
29 59.9926863181059 37.443793199906 2597.6226899462695
30 61.14023763522894 38.162871262901774 2417.486655550268
31 62.24690554051466 38.85655838137802 2249.926282910165
32 63.314142966505344 39.52575687569168 2094.0636252577956
33 64.34335121133323 40.17133699948599 1949.0820280732253
34 65.33588177370743 40.794138079279385 1814.2218500785045
35 66.2930381226889 41.39496961355559 1688.7764829624412
36 67.21607740457115 41.97461233279419 1572.0886489809884
37 68.10621208910162 42.533819221829745 1463.5469570339176
38 68.96461155719958 43.073316505878296 1362.582699172676
39 69.7924036322496 43.59380460152233 1268.6668707542046
40 70.59067605697587 44.095959033899625 1181.307398627265
41 71.36047791783113 44.58043132129699 1100.0465628278696
42 72.10282101876575 45.04784982830722 1024.45859827433
43 72.8186812061756 45.498820588666526 954.1474638955829
44 73.50899964676388 45.93392809884992 888.7447675037332
45 74.17468405999021 46.353736083463744 827.9078355378441
46 74.81660990672088 46.75878823343766 771.3179175650148
47 75.43562153563676 47.14960891798269 718.6785161309467
48 76.03253328890007 47.52670387124766 669.7138332089286
49 76.60813056852795 47.89056085457323 624.167325107157
50 77.16317086486914 48.24165029521065 581.800358262545
51 77.69838474853061 48.580425902341716 542.3909588778397
52 78.214476827053 48.9073252612066 505.732649850532
53 78.71212666758774 49.222770406117476 471.63336889945094
54 79.19198968678394 49.52716837310836 439.9144622203703
55 79.65469800905048 49.820911732944886 410.409748397707
56 80.10086129431708 50.104379105191896 382.9646476675163
57 80.53106753637839 50.377935654012106 357.43537196939786
58 80.94588383286641 50.641933566345024 333.68817154344384
59 81.34585712785972 50.89671251309231 311.59863412464637
60 81.73151492810162 51.14260009391353 291.0510330627655
61 82.10336599376544 51.3799122662147 271.9377209520167
62 82.46190100467129 51.60895375889144 254.15856559339238
63 82.80759320282681 51.83001847136844 237.62042533424133
64 83.14089901213319 52.04338985845792 222.23666103606092
65 83.46225863606817 52.24934130154091 207.92668211335732
66 83.77209663412839 52.44813646655746 194.6155242649818
67 84.0708224777862 52.64002964927461 182.2334566853747
68 84.35883108668884 52.825266108284175 170.7156166976405
69 84.63650334580208 53.00408238616645 160.00166989404852
70 84.90420660417563 53.17670661924036 150.03549400319983
71 85.16229515598333 53.34335883630573 140.76488482743162
72 85.41111070446821 53.50425124676878 132.1412827096647
73 85.65098280939975 53.659588518528224 124.11951809646608
74 85.88222931862938 53.80956804598586 116.65757486416118
75 86.10515678430941 53.95438020853254 109.71637016790369
76 86.32006086432025 54.09420861984807 103.25954966017598
77 86.52722670943173 54.22923036834147 97.25329700573813
78 86.72692933670548 54.35961624904647 91.66615669494082
79 86.9194339896273 54.48553098727585 86.46886922700486
80 87.10499648544102 54.6071334543276 81.6342177996771
81 87.28386355013902 54.72457687552523 77.13688570196685
82 87.45627314154756 54.838009030864775 72.95332366275072
83 87.6224547609305 54.94757244853118 69.0616264601885
84 87.78262975351912 55.053404591537515 65.44141814542981
85 87.93701159836172 55.15563803773133 62.0737452792161
86 88.0858061878725 55.254400653404 58.940977621975314
87 88.2292120974459 55.3498157607303 56.02671575705411
88 88.3674208454892 55.44200229925751 53.31570516306752
89 88.50061714421433 55.53107498165548 50.793756285128836
90 88.6289791415167 55.617144443931686 48.44767018616127
91 88.75267865425839 55.700317390307916 46.26516938872658
92 88.87188139326081 55.7806967329483 44.23483354500507
93 88.9867471803015 55.8583817267217 42.34603959785978
94 89.09743015739943 55.9334680991749 40.58890611944361
95 89.2040789886625 56.0060481758868 38.954241535708235
96 89.30683705496197 56.07621100136774 37.43349596552185
97 89.40584264168847 56.144042455662365 36.018716422051206
98 89.5012291198354 56.20962536680856 34.702505141678394
99 89.59312512064723 56.27303961929989 33.47798082210688
100 89.68165470406089 56.334362258693425 32.338742566558786
101 89.76693752116124 56.39366759250009 31.278836345142015
102 89.8490889708631 56.45102728748947 30.29272379765601
103 89.92822035102513 56.506510463536685 29.375253214372034
104 90.00443900419347 56.56018378413406 28.52163254273753
105 90.07784845816585 56.61211154368621 27.727404278568397
106 90.14854856156033 56.66235575170284 26.98842211016566
107 90.2166356145663 56.710976213999466 26.300829192981922
108 90.28220249504867 56.75803061101245 25.661037941001126
109 90.3453387801707 56.803574573330856 25.06571122894645
110 90.40613086369456 56.84766175454404 24.51174490682205
111 90.46466206911316 56.89034390150041 23.9962515351697
112 90.52101275876169 56.931670922069266 23.516545255818887
113 90.5752604390513 56.97169095049461 23.0701277188577
114 90.62747986196324 57.01045041042631 22.654674992086893
115 90.67774312293582 57.04799407571131 22.26802538436611
116 90.72611975527295 57.084365129024434 21.90816811905066
117 90.77267682119728 57.11960521841556 21.57323279817278
118 90.81747899966777 57.15375451184721 21.261479602160275
119 90.86058867107621 57.18685174979401 20.97129017374469
120 90.90206599893384 57.2189342959728 20.701159138293153
121 90.94196900865497 57.25003818626998 20.449686216131752
122 90.98035366354085 57.28019817593002 20.21556888553356
123 91.01727393806318 57.30944778506696 19.99759555792586
124 91.05278188854322 57.3378193425586 19.794639229558733
125 91.08692772131913 57.36534402838072 19.60565157637005
126 91.11975985849082 57.39205191443679 19.4296574611071
127 91.15132500132835 57.41797200393676 19.2657498239231
128 91.18166819142678 57.44313226937633 19.113084929678053
129 91.21083286968795 57.467559689166535 18.970877947039295
130 91.23886093320588 57.49128028296162 18.838398836220932
131 91.26579279013082 57.514319145731356 18.71496852381158
132 91.29166741258334 57.53670048062257 18.59995534465003
133 91.3165223876881 57.55844763065277 18.49277173210542
134 91.3403939667939 57.57958310927751 18.39287113941855
135 91.36331711294457 57.60012862987138 18.29974517597492
136 91.38532554666284 57.62010513416136 18.212920943502947
137 91.40645179010711 57.63953281964968 18.131958558241028
138 91.42672720965903 57.65843116606209 18.056448846090166
139 91.44618205699754 57.676818960856274 17.986011198674678
140 91.46484550871325 57.69471432382373 17.920291579078633
141 91.48274570451501 57.712134730817304 17.858960666808056
142 91.49990978407867 57.72909703663552 17.80171213225885
143 91.51636392258632 57.74561749709368 17.748261031650195
144 91.53213336500252 57.76171179031053 17.698342314012077
145 91.54724245913245 57.777395037238485 17.651709432405628
146 91.56171468750517 57.79268182146426 17.608133052097184
147 91.57557269812393 57.80758620830578 17.567399848920616
148 91.58883833412354 57.82212176323048 17.529311391527973
149 91.60153266237384 57.836301569618975 17.493683101675256
150 91.61367600106672 57.85013824589753 17.460343287092968
151 91.62528794632259 57.86364396206164 17.429132241875497
152 91.63638739785145 57.87683045561234 17.399901409674996
153 91.64699258370197 57.88970904692629 17.37251260531536
154 91.65712108413105 57.902290654079515 17.346837290747953
155 91.66678985462502 57.9145858071444 17.322755901555055
156 91.67601524810284 57.9266046619786 17.300157220472
157 91.68481303633014 57.938357013523905 17.27893779464624
158 91.69319843057232 57.94985230863247 17.25900139357903
159 91.7011861015136 57.96109965843727 17.24025850490985
160 91.70879019846825 57.97210785028289 17.222625865402158
161 91.71602436790909 57.982885359232355 17.20602602467189
162 91.72290177133743 57.99344035916499 17.190386939374367
163 91.72943510251814 58.00378073347993 17.175641595720773
164 91.73563660410194 58.01391408541919 17.161727658349974
165 91.74151808365727 58.02384774802394 17.148587143711882
166 91.74709092913218 58.0335887937369 17.136166116254373
167 91.75236612376688 58.04314404366349 17.124414405818825
168 91.75735426047619 58.05252007650391 17.11328534476718
169 91.76206555572107 58.06172323716772 17.102735523458737
170 91.76650986288696 58.070759645082305 17.092724562800125
171 91.77069668518685 58.07963520220609 17.083214902672204
172 91.77463518810566 58.08835560075697 17.074171605129326
173 91.77833421140251 58.096926330666044 17.06556217133651
174 91.78180228068634 58.10535268676654 17.057356371287792
175 91.78504761858022 58.11363977572719 17.049526085411905
176 91.78807815548888 58.121792522739234 17.042045157236114
177 91.79090153998357 58.12981567796579 17.03488925633612
178 91.79352514881788 58.13771382276199 17.028035750854027
179 91.79595609658763 58.14549137567412 17.02146358891571
180 91.79820124504745 58.153152598225496 17.015153188327368
181 91.80026721209623 58.160701600496786 17.00908633397239
182 91.80216038044333 58.16814234650797 17.00324608237138
183 91.8038869059667 58.17547865940906 16.997616672905185
184 91.80545272577412 58.18271422648634 16.992183445235586
185 91.80686356597775 58.1898526039907 16.986932762491485
186 91.80812494919262 58.19689722179439 16.981851939816867
187 91.80924220176846 58.203851387882246 16.976929177908037
188 91.81022046076458 58.210718292683374 16.972153501190466
189 91.81106468067695 58.217501013248814 16.967514700311433
190 91.81177963992607 58.22420251728079 16.963003278647587
191 91.81236994711442 58.23082566701875 16.95861040254747
192 91.81284004706139 58.23737322298733 16.954327855046735
193 91.81319422662388 58.243847847611065 16.95014799281583
194 91.81343662030994 58.2502521087007 16.946063706112394
195 91.813571215693 58.25658848281558 16.942068381530177
196 91.81360185863359 58.26285935850653 16.938155867347763
197 91.81353225831556 58.269067039443534 16.934320441297388
198 91.81336599210333 58.27521374743221 16.930556780583068
199 91.81310651022645 58.28130162532313 16.92685993399243
200 91.81275714029775 58.28733273981771 16.92322529595517
201 91.81232109167094 58.29330908417441 16.91964858241272
202 91.81180145964325 58.29923258081877 16.916125808372435
203 91.8112012295088 58.30510508386064 16.91265326702914
204 91.8105232804679 58.310928381522025 16.909227510343694
205 91.80977038939744 58.31670419847858 16.905845330977638
206 91.80894523448721 58.32243419811795 16.90250374548941
207 91.80805039874711 58.32811998471781 16.89919997870325
208 91.80708837338962 58.3337631055465 16.89593144916954
209 91.80606156109211 58.33936505288908 16.892695755640194
210 91.80497227914323 58.344927266001264 16.889490664488264
211 91.80382276247742 58.35045113299404 16.886314098005325
212 91.80261516660167 58.35593799265121 16.883164123517187
213 91.80135157041815 58.36138913618239 16.880038943257773
214 91.80003397894666 58.36680580891373 16.876936884951387
215 91.79866432595024 58.3721892119185 16.873856393051227
216 91.79724447646751 58.37754050358975 16.870796020590706
217 91.795776229255 58.38286080115708 16.867754421602914
218 91.79426131914263 58.38815118214952 16.864730344069475
219 91.79270141930566 58.393412685806425 16.86172262336166
220 91.79109814345564 58.398646314438174 16.858730176139776
221 91.78945304795377 58.40385303473859 16.855751994677828
222 91.78776763384889 58.40903377905066 16.852787141584447
223 91.78604334884326 58.41418944658731 16.849834744893318
224 91.78428158918841 58.41932090460878 16.846893993495122
225 91.7824837015135 58.424428989558166 16.843964132888882
226 91.7806509845889 58.42951450815658 16.841044461230396
227 91.77878469102696 58.43457823845943 16.83813432565561
228 91.77688602892236 58.43962093087515 16.83523311886159
229 91.77495616343424 58.44464330914769 16.8323402759255
230 91.77299621831199 58.44964607130415 16.829455271345918
231 91.77100727736688 58.45462989056868 16.826577616290837
232 91.7689903858914 58.45959541624396 16.823706856037756
233 91.76694655202814 58.46454327456128 16.8208425675917
234 91.76487674809005 58.4694740695005 16.81798435747154
235 91.76278191183368 58.47438838358079 16.815131859648016
236 91.76066294768735 58.4792867786233 16.812284733628683
237 91.75852072793549 58.484169796486746 16.809442662673792
238 91.756356093861 58.48903795977682 16.806605352139083
239 91.754169856847 58.49389177253042 16.803772527932534
240 91.75196279943938 58.49873172087552 16.80094393508024
241 91.74973567637166 58.50355827366766 16.798119336390865
242 91.74748921555333 58.50837188310373 16.795298511214934
243 91.7452241190232 58.513172985314014 16.792481254289616
244 91.74294106386874 58.51796200093317 16.789667374664514
245 91.74064070311279 58.522739335650876 16.78685669470291
246 91.7383236665688 58.527505380743 16.784049049151616
247 91.73599056166569 58.53226051358379 16.781244284276955
248 91.73364197424326 58.537005098139936 16.778442257060536
249 91.73127846931948 58.54173948544704 16.77564283445098
250 91.72890059183045 58.54646401406916 16.772845892667963
251 91.7265088673441 58.551179010542036 16.77005131655549
252 91.72410380274843 58.55588478980054 16.76725899897945
253 91.72168588691542 58.560581655590944 16.764468840267618
254 91.71925559134125 58.56526990086856 16.7616807476887
255 91.71681337076383 58.5699498081812 16.758894634967778
256 91.71435966375832 58.57462165003907 16.756110421835775
257 91.71189489331157 58.57928568927147 16.753328033610025
258 91.70941946737605 58.58394217937084 16.750547400804326
259 91.7069337794042 58.588591364824545 16.747768458765716
260 91.70443820886365 58.59323348143495 16.74499114733787
261 91.7019331217343 58.597868756628024 16.742215410546667
262 91.69941887098761 58.60249740975104 16.739441196308054
263 91.6968957970489 58.607119652359664 16.7366684561572
264 91.69436422824317 58.611735688494875 16.73389714499487
265 91.69182448122523 58.616345714949986 16.731127220853367
266 91.68927686139432 58.62094992152826 16.728358644677204
267 91.68672166329418 58.62554849129126 16.725591380120232
268 91.68415917099883 58.6301416007985 16.72282539335646
269 91.6815896584846 58.63472942033847 16.720060652903737
270 91.67901338998904 58.63931211415152 16.717297129460825
271 91.67643062035697 58.64388984064478 16.714534795754517
272 91.67384159537433 58.64846275259947 16.71177362639808
273 91.67124655209004 58.65303099737084 16.709013597760293
274 91.66864571912659 58.65759471708098 16.706254687841774
275 91.66603931697942 58.66215404880482 16.70349687616208
276 91.6634275583058 58.66670912474948 16.70074014365298
277 91.66081064820332 58.67126007242726 16.697984472560197
278 91.65818878447861 58.67580701482248 16.695229846351978
279 91.6555621579064 58.68035007055243 16.69247624963267
280 91.65293095247947 58.68488935402251 16.689723668064747
281 91.6502953456496 58.68942497557596 16.686972088294056
282 91.64765550856009 58.6939570416382 16.68422149788139
283 91.64501160626992 58.69848565485606 16.681471885238977
284 91.64236379796995 58.70301091423205 16.678723239570257
285 91.63971223719153 58.70753291525393 16.675975550815647
286 91.63705707200758 58.71205175001953 16.673228809600197
287 91.63439844522657 58.7165675073573 16.670483007186267
288 91.63173649457963 58.72108027294243 16.667738135428994
289 91.62907135290097 58.72559012940897 16.66499418673493
290 91.62640314830192 58.73009715645787 16.66225115402337
291 91.62373200433878 58.73460143096123 16.659509030690714
292 91.62105804017467 58.739103027062804 16.656767810577175
293 91.6183813707357 58.743602016275005 16.654027487935746
294 91.61570210686149 58.74809846757239 16.65128805740349
295 91.61302035545042 58.752592447481845 16.64854951397425
296 91.61033621959972 58.757084020169586 16.645811852974653
297 91.60764979874051 58.761573247525035 16.643075070040172
298 91.60496118876814 58.76606018924176 16.640339161093582
299 91.60227048216781 58.77054490289548 16.637604122325317
300 91.59957776813573 58.775027444019344 16.634869950174416
301 91.59688313269609 58.779507866176516 16.632136641311508
302 91.59418665881371 58.78398622103019 16.629404192622214
303 91.59148842650279 58.788462558411105 16.62667260119267
304 91.58878851293179 58.79293692638266 16.62394186429486
305 91.58608699252453 58.797409371303736 16.62121197937446
306 91.58338393705775 58.80187993788926 16.61848294403807
307 91.58067941575518 58.80634866926863 16.615754756042175
308 91.57797349537827 58.810815607042066 16.613027413282946
309 91.57526624031368 58.81528079133495 16.610300913785913
310 91.57255771265768 58.81974426085022 16.60757525569771
311 91.56984797229758 58.82420605291897 16.604850437276852
312 91.56713707699018 58.82866620354914 16.60212645688644
313 91.56442508243752 58.83312474747258 16.599403312986748
314 91.56171204235991 58.8375817181904 16.596681004128328
315 91.55899800856632 58.842037148016665 16.593959528945955
316 91.55628303102232 58.846491068120635 16.59123888615238
317 91.55356715791561 58.85094350856741 16.58851907453325
318 91.55085043571918 58.85539449835719 16.585800092941664
319 91.54813290925227 58.859844065463115 16.58308194029392
320 91.54541462173913 58.86429223686774 16.5803646155649
321 91.54269561486568 58.86873903859828 16.57764811778372
322 91.53997592883422 58.873184495760526 16.57493244603041
323 91.53725560241614 58.87762863257161 16.57221759943177
324 91.53453467300274 58.88207147239157 16.569503577158915
325 91.53181317665434 58.886513037753836 16.566790378423672
326 91.52909114814751 58.89095335039456 16.564078002475615
327 91.52636862102078 58.895392431280996 16.56136644859971
328 91.52364562761852 58.8998303006388 16.55865571611383
329 91.5209221991335 58.90426697797838 16.555945804366342
330 91.51819836564772 58.90870248212034 16.553236712734204
331 91.51547415617196 58.913136831219965 16.550528440620695
332 91.5127495986838 58.91757004279088 16.54782098745381
333 91.51002472016434 58.922002133727844 16.545114352684283
334 91.50729954663363 58.92643312032876 16.54240853578433
335 91.50457410318484 58.93086301831586 16.53970353624582
336 91.50184841401715 58.93529184285619 16.53699935357904
337 91.49912250246759 58.93971960858131 16.534295987311978
338 91.4963963910416 58.94414632960636 16.53159343698774
339 91.49367010144265 58.94857201954838 16.52889170216496
340 91.4909436546007 58.952996691544016 16.52619078241584
341 91.48821707069972 58.95742035826661 16.523490677325494
342 91.48549036920417 58.96184303194265 16.520791386490888
343 91.48276356888461 58.96626472436765 16.518092909520394

In [50]:
def func(x, w, b):
    return w * x + b

def squared_error(y_hat, y): 
    return (y_hat - y)**2

In [51]:
best_w = None
best_b = None
best_cost = None

learning_rate = 0.01
w, b = 0, 0
for step in range(0,100000):

    if step != 0:
        w = w - learning_rate * dj_dw
        b = b - learning_rate * dj_db

    y_hat = []
    for x in x_train:
        y_hat.append(func(x, w, b))


    sum_of_squared_errors = 0
    dj_dw = 0
    dj_db = 0
    for i in range(len(y_hat)):
        sum_of_squared_errors += squared_error(y_hat[i], y_train[i])
        dj_dw += (y_hat[i] - y_train[i]) * x_train[i]
        dj_db += (y_hat[i] - y_train[i])

    m = len(x_train)
    cost = ( 1/ (2 * m) ) * sum_of_squared_errors
    dj_dw = ( 1/ m ) * dj_dw
    dj_db = ( 1/ m ) * dj_db

    if best_cost is None or cost < best_cost:
        best_cost = cost
        best_w = w
        best_b = b

    if step % 1000 == 0:
        print('step: ', step, w, b, 'cost: ', cost, 'dj_dw', dj_dw, 'dj_db', dj_db)
    if best_cost is not None and (abs(dj_dw) < 1e-6 and abs(dj_db) < 1e-6):
        break

print('Best Parameters are:', step, w, b, cost)

step:  0 0 0 cost:  21061.125 dj_dw -328.253 dj_db -204.5
step:  1000 89.76875965777637 61.7270251435378 cost:  14.909659553369305 dj_dw 0.2482408953309442 dj_db -0.3997220392288625
step:  2000 87.46385453503443 65.43842561469245 cost:  12.997497941491769 dj_dw 0.21357420104363795 dj_db -0.34390109274294406
step:  3000 85.48082805015741 68.63153120401465 cost:  11.582109912807924 dj_dw 0.18374869012062392 dj_db -0.29587550843568045
step:  4000 83.77473004164355 71.37872148536624 cost:  10.534435250113331 dj_dw 0.15808829416676376 dj_db -0.2545566685870805
step:  5000 82.30688761147258 73.74226826790645 cost:  9.758943175425431 dj_dw 0.13601135733891803 dj_db -0.2190079802980449
step:  6000 81.044028508972 75.77574713945624 cost:  9.18492150694597 dj_dw 0.11701745168862605 dj_db -0.1884236453141644
step:  7000 79.95752693360652 77.5252518886689 cost:  8.760028865694128 dj_dw 0.10067603373422607 dj_db -0.1621103946311469
step:  8000 79.02275466096435 79.03043933385932 cost:  8.445521998613406 dj_dw 0.08661668513697052 dj_db -0.13947177385120804
step:  9000 78.21852278361355 80.32542824210847 cost:  8.21272302814982 dj_dw 0.07452071626043613 dj_db -0.11999462308043007
step:  10000 77.52660141251981 81.4395727148425 cost:  8.04040449929883 dj_dw 0.06411394228701035 dj_db -0.10323744490108311
step:  11000 76.93130645187549 82.39812757057679 cost:  7.912853783218719 dj_dw 0.05516046814696818 dj_db -0.08882039674868261
step:  12000 76.4191440805815 83.2228208073496 cost:  7.81844034270795 dj_dw 0.04745734137799099 dj_db -0.07641668084813583
step:  13000 75.9785048816779 83.932346121118 cost:  7.748555217614037 dj_dw 0.04082995170851274 dj_db -0.0657451365408311
step:  14000 75.59940068642108 84.5427866442486 cost:  7.696826028602706 dj_dw 0.035128073088775594 dj_db -0.05656386708757092
step:  15000 75.27323816792747 85.06797950918092 cost:  7.658535920483571 dj_dw 0.030222458447515994 dj_db -0.04866475648611868
step:  16000 74.99262405233304 85.51982950098925 cost:  7.630193462235128 dj_dw 0.026001909991181606 dj_db -0.04186875201054363
step:  17000 74.75119753209869 85.90857890854885 cost:  7.609214285653486 dj_dw 0.022370758631740685 dj_db -0.0360218055426363
step:  18000 74.54348608269771 86.24303969114881 cost:  7.5936854332798145 dj_dw 0.019246695413097054 dj_db -0.030991381692615505
step:  19000 74.36478141441867 86.53079322317244 cost:  7.582190927997324 dj_dw 0.016558905776167993 dj_db -0.026663453559554757
step:  20000 74.21103274742487 86.77836214455229 cost:  7.573682659098073 dj_dw 0.014246464373142882 dj_db -0.022939918031871304
step:  21000 74.07875499088945 86.99135821240985 cost:  7.567384811745683 dj_dw 0.01225695404508631 dj_db -0.019736372039479495
step:  22000 73.96494974485931 87.17460950530199 cost:  7.562723125362183 dj_dw 0.010545277658308075 dj_db -0.016980199351147952
step:  23000 73.86703733416235 87.3322698634691 cost:  7.559272530464947 dj_dw 0.009072635867144166 dj_db -0.014608924549425712
step:  24000 73.78279833373922 87.46791304581753 cost:  7.5567183892882115 dj_dw 0.007805647631490645 dj_db -0.012568796872064542
step:  25000 73.71032325992788 87.58461373793554 cost:  7.554827805970042 dj_dw 0.006715593553957196 dj_db -0.010813571818848306
step:  26000 73.64796928733112 87.68501724738617 cost:  7.553428390262134 dj_dw 0.005777764884075627 dj_db -0.009303462906662691
step:  27000 73.5943230101475 87.77139946609468 cost:  7.552392538361475 dj_dw 0.0049709034335491484 dj_db -0.008004239811375175
step:  28000 73.54816840386006 87.84571845902452 cost:  7.551625797532339 dj_dw 0.004276719707458317 dj_db -0.006886452453424377
step:  29000 73.5084592610567 87.90965884852487 cost:  7.551058253563236 dj_dw 0.003679478328407093 dj_db -0.005924763439206041
step:  30000 73.47429547657214 87.96467000042936 cost:  7.550638155735417 dj_dw 0.003165641355076391 dj_db -0.005097373727210197
step:  31000 73.44490264439524 88.0119988774896 cost:  7.550327198004334 dj_dw 0.0027235614110689235 dj_db -0.004385528499549688
step:  32000 73.4196145038565 88.05271830484656 cost:  7.550097026115442 dj_dw 0.0023432176700527068 dj_db -0.0037730920370411996
step:  33000 73.39785783719515 88.08775128824405 cost:  7.549926652160576 dj_dw 0.0020159887076998118 dj_db -0.003246181964442485
step:  34000 73.37913947617177 88.11789193621945 cost:  7.549800540824365 dj_dw 0.0017344570763212865 dj_db -0.002792854572116236
step:  35000 73.36303512320015 88.14382346052248 cost:  7.549707192817242 dj_dw 0.0014922411709636187 dj_db -0.0024028340820715735
step:  36000 73.34917973360085 88.16613366278607 cost:  7.549638096329358 dj_dw 0.001283850573457812 dj_db -0.0020672797229887387
step:  37000 73.33725924096875 88.18532825849185 cost:  7.549586950892115 dj_dw 0.001104561599828931 dj_db -0.0017785853317207057
step:  38000 73.32700343808604 88.20184234025402 cost:  7.549549092878815 dj_dw 0.0009503102254052227 dj_db -0.0015302069415194333
step:  39000 73.31817985201306 88.21605024026059 cost:  7.549521070258555 dj_dw 0.0008175999642165976 dj_db -0.001316514446690083
step:  40000 73.3105884745194 88.22827401542978 cost:  7.5495003278270065 dj_dw 0.0007034226125511485 dj_db -0.0011326639824460472
step:  41000 73.3040572284051 88.23879074762264 cost:  7.549484974214119 dj_dw 0.0006051900605209918 dj_db -0.0009744881268716199
step:  42000 73.29843806694973 88.24783882438172 cost:  7.549473609421577 dj_dw 0.0005206756263159325 dj_db -0.000838401436017951
step:  43000 73.29360361806984 88.25562334257016 cost:  7.549465197166538 dj_dw 0.00044796358291362043 dj_db -0.0007213191710775391
step:  44000 73.28944429711827 88.26232075739522 cost:  7.549458970388876 dj_dw 0.00038540573341805384 dj_db -0.0006205873752094249
step:  45000 73.28586582287876 88.26808288219911 cost:  7.549454361308553 dj_dw 0.0003315840504738432 dj_db -0.0005339227151826738
step:  46000 73.28278708045147 88.27304032968034 cost:  7.549450949652773 dj_dw 0.00028527853383468005 dj_db -0.0004593607236339873
step:  47000 73.28013828258425 88.27730547255123 cost:  7.549448424334486 dj_dw 0.000245439555192443 dj_db -0.0003952112701502604
step:  48000 73.2778593877733 88.28097499074173 cost:  7.549446555085976 dj_dw 0.00021116406653002665 dj_db -0.0003400202498179775
step:  49000 73.27589873927548 88.28413206288614 cost:  7.549445171462274 dj_dw 0.0001816751294404876 dj_db -0.0002925366229457419
step:  50000 73.27421189418148 88.28684825177164 cost:  7.549444147299824 dj_dw 0.00015630430494380693 dj_db -0.0002516840565268315
step:  51000 73.2727606160076 88.28918512648517 cost:  7.549443389211449 dj_dw 0.00013447650119828106 dj_db -0.0002165365267880285
step:  52000 73.27151200797285 88.2911956580262 cost:  7.5494428280720705 dj_dw 0.0001156969372395622 dj_db -0.00018629732886665806
step:  53000 73.27043776731198 88.29292542002622 cost:  7.549442412714969 dj_dw 9.9539928385776e-05 dj_db -0.000160281016993243
step:  54000 73.2695135437244 88.29441362178538 cost:  7.549442105266344 dj_dw 8.563923620297231e-05 dj_db -0.00013789786773562202
step:  55000 73.26871838741444 88.29569399704874 cost:  7.549441877691878 dj_dw 7.367976760589792e-05 dj_db -0.00011864051195213202
step:  56000 73.26803427421304 88.29679556866348 cost:  7.549441709240481 dj_dw 6.339043153532249e-05 dj_db -0.00010207243463848195
step:  57000 73.26744569701583 88.29774330645343 cost:  7.5494415845523095 dj_dw 5.453799526478065e-05 dj_db -8.781807946434128e-05
step:  58000 73.26693931427633 88.29855869322112 cost:  7.549441492257749 dj_dw 4.6921796410970273e-05 dj_db -7.555433661347402e-05
step:  59000 73.26650364758713 88.2992602117087 cost:  7.5494414239409835 dj_dw 4.036919538859725e-05 dj_db -6.50032181018408e-05
step:  60000 73.26612882149345 88.29986376355419 cost:  7.54944137337271 dj_dw 3.47316609913643e-05 dj_db -5.59255571962088e-05
step:  61000 73.26580633964221 88.30038302974128 cost:  7.549441335941926 dj_dw 2.9881405123314643e-05 dj_db -4.81155861583223e-05
step:  62000 73.26552889219087 88.30082978071225 cost:  7.549441308235508 dj_dw 2.5708484507447338e-05 dj_db -4.13962730287191e-05
step:  63000 73.2652901901122 88.30121414317414 cost:  7.549441287727177 dj_dw 2.2118309924934465e-05 dj_db -3.561530792239864e-05
step:  64000 73.26508482263763 88.30154482964545 cost:  7.549441272546797 dj_dw 1.902950096580961e-05 dj_db -3.0641651259581217e-05
step:  65000 73.26490813460944 88.30182933594668 cost:  7.549441261310264 dj_dw 1.637204244560782e-05 dj_db -2.6362562749682183e-05
step:  66000 73.26475612095999 88.302074111111 cost:  7.549441252992929 dj_dw 1.4085696374621648e-05 dj_db -2.268104645963831e-05
step:  67000 73.26462533592672 88.30228470356847 cost:  7.549441246836375 dj_dw 1.2118637193599586e-05 dj_db -1.951365173151013e-05
step:  68000 73.26451281494609 88.30246588691368 cost:  7.549441242279402 dj_dw 1.0426276623694736e-05 dj_db -1.678858183140619e-05
step:  69000 73.26441600745396 88.30262176811172 cost:  7.549441238906173 dj_dw 8.97025327232607e-06 dj_db -1.4444066295027369e-05
step:  70000 73.26433271907085 88.30275588059266 cost:  7.549441236409402 dj_dw 7.717562721036112e-06 dj_db -1.2426960968999385e-05
step:  71000 73.2642610618611 88.30287126434506 cost:  7.549441234561259 dj_dw 6.639809616200883e-06 dj_db -1.0691543233557846e-05
step:  72000 73.26419941153846 88.30297053482447 cost:  7.549441233193172 dj_dw 5.712564136395315e-06 dj_db -9.19847553859654e-06
step:  73000 73.26414637064694 88.30305594224008 cost:  7.549441232180596 dj_dw 4.914807909687605e-06 dj_db -7.913913880959928e-06
step:  74000 73.26410073688446 88.30312942256081 cost:  7.5494412314311035 dj_dw 4.228457980796444e-06 dj_db -6.808740427762435e-06
step:  75000 73.26406147584993 88.3031926413981 cost:  7.549441230876276 dj_dw 3.637956205911526e-06 dj_db -5.857903924303779e-06
step:  76000 73.26402769759578 88.30324703176201 cost:  7.5494412304655985 dj_dw 3.129917831579121e-06 dj_db -5.039851070402316e-06
step:  77000 73.26399863645479 88.30329382654386 cost:  7.549441230161659 dj_dw 2.6928266766053826e-06 dj_db -4.336038832282914e-06
step:  78000 73.26397363368488 88.30333408646221 cost:  7.549441229936626 dj_dw 2.3167750334470343e-06 dj_db -3.7305135644298084e-06
step:  79000 73.26395212253698 88.30336872410679 cost:  7.549441229770091 dj_dw 1.9932387157102953e-06 dj_db -3.209549580181677e-06
step:  80000 73.26393361540828 88.30339852462463 cost:  7.54944122964679 dj_dw 1.714884154383848e-06 dj_db -2.76133784874825e-06
step:  81000 73.26391769278906 88.30342416351789 cost:  7.549441229555566 dj_dw 1.4754015872734763e-06 dj_db -2.375718651137504e-06
step:  82000 73.26390399375416 88.30344622195494 cost:  7.549441229487955 dj_dw 1.269362574163324e-06 dj_db -2.0439509758792456e-06
step:  83000 73.26389220778161 88.30346519994399 cost:  7.549441229437982 dj_dw 1.0920969201559196e-06 dj_db -1.7585143818147722e-06
step:  84000 73.26388206771313 88.30348152766808 cost:  7.54944122940095 dj_dw 9.395862100210668e-07 dj_db -1.5129389036398302e-06
step:  85000 73.2638733436992 88.30349557523515 cost:  7.549441229373587 dj_dw 8.083734863717496e-07 dj_db -1.3016579221887998e-06
step:  86000 73.26386583798865 88.3035076610679 cost:  7.549441229353297 dj_dw 6.954846834735424e-07 dj_db -1.11988211415337e-06
Best Parameters are: 86753 73.26386088630811 88.30351563435461 7.549441229341614

In [53]:
x_valid = validation_rows['GrLivArea'].to_numpy() / 1000
y_valid = validation_rows['SalePrice'].to_numpy() / 1000

sse = 0
valid_y_hat = []
for i in range(len(x_valid)):
    y_hat = func(x_valid[i], best_w, best_b)
    sse += (y_hat - y_valid[i])**2
    valid_y_hat.append(y_hat * 1000)

m = len(x_valid)
cost = ( 1 / (2 * m)) * sse

print('cost: ', cost)

cost:  2246.2637888317954

In [54]:
# validation_rows['PredictedSales'] = predictions * 1000
validation_rows['PredictedSales'] = valid_y_hat

C:\Users\alirm\AppData\Local\Temp\ipykernel_65228\3410635853.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  validation_rows['PredictedSales'] = valid_y_hat

In [55]:
test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
test_rows.head()

     Id  GrLivArea
0  1461        896
1  1462       1329
2  1463       1629
3  1464       1604
4  1465       1280

In [56]:
x_test = test_rows['GrLivArea'].to_numpy() / 1000
predictions = best_w * x_test + best_b

test_rows['SalePrice'] = predictions * 1000
test_rows

        Id  GrLivArea      SalePrice
0     1461        896  153947.934988
1     1462       1329  185671.186752
2     1463       1629  207650.345018
3     1464       1604  205818.748496
4     1465       1280  182081.257569
...    ...        ...            ...
1454  2915       1092  168307.651722
1455  2916       1092  168307.651722
1456  2917       1224  177978.481359
1457  2918        970  159369.460694
1458  2919       2000  234831.237407

[1459 rows x 3 columns]

In [57]:
test_rows[['Id', 'SalePrice']].to_csv('submission.csv', index=False)

In [58]:
# Use the direct formula method
import numpy as np

test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
x_mean = x_train.mean()
y_mean = y_train.mean()

best_w_dir = np.sum((x_train - x_mean) * (y_train - y_mean)) / np.sum((x_train - x_mean)**2)
best_b_dir = y_mean - best_w_dir * x_mean

predictions = best_w_dir * x_test + best_b_dir
test_rows['SalePrice'] = predictions * 1000

print(best_b_dir, best_w_dir)

88.30358211933743 73.26381959688686

In [59]:
test_rows[['Id', 'SalePrice']].to_csv('submission_dir.csv', index=False)